apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-replit-code-v1-latest
spec:
  # https://docs.coreweave.com/coreweave-kubernetes/storage
  storageClassName: shared-nvme-ord1 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 149Gi
